# fly.toml file generated for unusual-database on 2023-02-21T17:41:25+08:00

app = "unusual-database"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
OTEL_EXPORTER_OTLP_ENDPOINT = "https://otel-exporter.internal:4317"
OTEL_SERVICE_NAME = "unusual-database"
SERVER_ADDR = "fly-global-services:1729"
RUST_LOG = "unusual_database=debug"

[experimental]
auto_rollback = true

[[services]]
internal_port = 1729
protocol = "udp"

[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"

[[services.ports]]
port = 1729
