# fly.toml file generated for prime-time on 2023-02-19T19:04:49+08:00

app = "prime-time"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
RUST_LOG = "info"

[experimental]
auto_rollback = true

[[services]]
http_checks = []
internal_port = 1729
processes = ["app"]
protocol = "tcp"
script_checks = []

[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"

[[services.ports]]
port = 1729

[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
restart_limit = 0
timeout = "2s"
