# fly.toml file generated for budget-chat on 2023-02-21T14:23:29+08:00

app = "budget-chat"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
OTEL_EXPORTER_OTLP_ENDPOINT = "https://api.honeycomb.io"
OTEL_EXPORTER_OTLP_HEADERS = "x-honeycomb-team=QLLy20BDjNUOmUcfk2kf6K"
OTEL_SERVICE_NAME = "budget-chat"
RUST_LOG = "budget_chat=debug"

[experimental]
auto_rollback = true

[[services]]
http_checks = []
internal_port = 1729
processes = ["app"]
protocol = "tcp"
script_checks = []

[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"

[[services.ports]]
port = 1729
