# fly.toml file generated for means-to-an-end on 2023-02-20T11:09:21+08:00

app = "means-to-an-end"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
OTEL_EXPORTER_OTLP_ENDPOINT = "https://api.honeycomb.io:443"
OTEL_SERVICE_NAME = "means-to-an-end"
RUST_LOG = "means_to_an_end=debug"

[experimental]
auto_rollback = true

[[services]]
http_checks = []
internal_port = 1729
processes = ["app"]
protocol = "tcp"
script_checks = []
[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"

[[services.ports]]
port = 1729
